// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sprint_1.Data;

#nullable disable

namespace Sprint_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoPatio", b =>
                {
                    b.Property<long>("MotosId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PatiosId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("MotosId", "PatiosId");

                    b.HasIndex("PatiosId");

                    b.ToTable("MotoPatio");
                });

            modelBuilder.Entity("Sprint_1.Models.Chaveiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("MotoId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("MotoId")
                        .IsUnique();

                    b.ToTable("CHAVEIRO");
                });

            modelBuilder.Entity("Sprint_1.Models.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<long?>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RG");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("FUNCIONARIO");
                });

            modelBuilder.Entity("Sprint_1.Models.Moto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Sprint_1.Models.Patio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOCALIZACAO");

                    b.HasKey("Id");

                    b.ToTable("PATIO");
                });

            modelBuilder.Entity("MotoPatio", b =>
                {
                    b.HasOne("Sprint_1.Models.Moto", null)
                        .WithMany()
                        .HasForeignKey("MotosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sprint_1.Models.Patio", null)
                        .WithMany()
                        .HasForeignKey("PatiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sprint_1.Models.Chaveiro", b =>
                {
                    b.HasOne("Sprint_1.Models.Moto", "Moto")
                        .WithOne("Chaveiro")
                        .HasForeignKey("Sprint_1.Models.Chaveiro", "MotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Sprint_1.Models.Funcionario", b =>
                {
                    b.HasOne("Sprint_1.Models.Patio", "Patio")
                        .WithMany("Funcionarios")
                        .HasForeignKey("PatioId");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint_1.Models.Moto", b =>
                {
                    b.Navigation("Chaveiro")
                        .IsRequired();
                });

            modelBuilder.Entity("Sprint_1.Models.Patio", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
